fitnessTracker/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace fitnessTracker.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

fitnessTracker/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace fitnessTracker.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

fitnessTracker/Pages/List/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using fitnessTracker.core;
using fitnessTracker.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace fitnessTracker
{
    public class DeleteModel : PageModel
    {
        private readonly IPlanData planData;

        public FitnessPlan FitnessPlan { get; set; }

        public DeleteModel(IPlanData planData)
        {
            this.planData = planData;
        }

        public IActionResult OnGet(int fitnessPlanId)
        {
            FitnessPlan = planData.GetById(fitnessPlanId);
            if (FitnessPlan == null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }

        public IActionResult OnPost(int fitnessPlanId)
        {
            var plan = planData.Delete(fitnessPlanId);
            planData.Commit();

            if (plan == null)
            {
                return RedirectToPage("./NotFound");
            }

            TempData["Message"] = "Fitness Plan Deleted";
            return RedirectToPage("./List");
        }
    }
}

fitnessTracker/Pages/List/Detail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using fitnessTracker.core;
using fitnessTracker.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace fitnessTracker
{
    public class DetailModel : PageModel
    {
        public FitnessPlan FitnessPlan { get; set; }

        [TempData]
        public string Message { get; set; }

        private readonly IPlanData planData;

        public DetailModel(IPlanData planData)
        {
            this.planData = planData;
        }

        public IActionResult OnGet(int fitnessPlanId)
        {
            FitnessPlan = planData.GetById(fitnessPlanId);
            if (FitnessPlan == null)
            {
                return Redirect("../NotFound");
            }
            return Page();
        }
    }
}

fitnessTracker/Pages/List/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using fitnessTracker.core;
using fitnessTracker.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace fitnessTracker
{
    public class EditModel : PageModel
    {
        private readonly IPlanData planData;

        [BindProperty]
        public FitnessPlan FitnessPlan { get; set; }

        public EditModel(IPlanData planData)
        {
            this.planData = planData;
        }

        public IActionResult OnGet(int? fitnessPlanId)
        {
            if (fitnessPlanId.HasValue)
            {
                FitnessPlan = planData.GetById(fitnessPlanId.Value);
            }
            else
            {
                FitnessPlan = new FitnessPlan();
                FitnessPlan.CustomerName = "New user";
            }
            if (FitnessPlan == null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            if (FitnessPlan.Id > 0)
            {
                planData.Update(FitnessPlan);
            }
            else
            {
                planData.Add(FitnessPlan);
            }
            planData.Commit();
            TempData["Message"] = "Data saved!";
            return RedirectToPage("./Detail", new { fitnessPlanId = FitnessPlan.Id });
        }
    }
}

fitnessTracker/Pages/List/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using fitnessTracker.core;
using fitnessTracker.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;

namespace fitnessTracker
{
    public class ListModel : PageModel
    {
        private readonly IConfiguration config;
        private readonly IPlanData planData;

        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; }


        public string Message { get; set; }
        public IEnumerable<FitnessPlan> FitnessPlans { get; set; }

        public ListModel(IConfiguration config, IPlanData planData)
        {
            this.config = config;
            this.planData = planData;
        }

        public void OnGet()
        { 
            FitnessPlans = planData.GetPlansByName(SearchTerm);
        }
    }
}

fitnessTracker/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace fitnessTracker.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

fitnessTracker/ViewComponents/FitnessPlanCountViewComponent.cs
using fitnessTracker.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace fitnessTracker.ViewComponents
{
    public class FitnessPlanCountViewComponent : ViewComponent
    {
        private IPlanData planData;

        public FitnessPlanCountViewComponent(IPlanData planData)
        {
            this.planData = planData;
        }

        public IViewComponentResult Invoke()
        {
            var count = planData.GetCount();

            return View(count);
        }
    }
}

fitnessTracker/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<div id="react-Test-Container">Container for the react component</div>
<div id="buttonMound">Button will be here</div>

@section Scripts {
    <partial name="_ReactScriptsPartial" />
    <script src="~/React/Components/react_test.js"></script>
    <script src="~/React/Components/hello_react.js"></script>
}

fitnessTracker/Pages/List/Delete.cshtml
@page "{fitnessPlanId}"
@model fitnessTracker.DeleteModel
@{
    
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h2>Delete!</h2>

    <div class="alert alert-danger">
        Are you sure you want to delete @Model.FitnessPlan.CustomerName ?
    </div>
    <form method="post">
        <button type="submit" class="btn btn-danger">Yes!</button>
        <a asp-page="List" class="btn btn-default">Cancel</a>
    </form>
</body>
</html>

fitnessTracker/Pages/List/Detail.cshtml
@page "{fitnessPlanId:Int}"
@model fitnessTracker.DetailModel
@{
    ViewData["Title"] = "Details for " + Model.FitnessPlan.CustomerName  ;
}

<h1>Detail</h1>

<h2>@Model.FitnessPlan.CustomerName</h2>

<div>
    Pushups: @Model.FitnessPlan.Pushups
</div>

<div>
    id: @Model.FitnessPlan.Id
</div>

@if(Model.Message != null)
{
    <div class="alert alert-info" >@Model.Message</div>
}
 
<a asp-page="./List" class="btn btn-primary">All Plans</a>

fitnessTracker/Pages/List/Edit.cshtml
@page "{fitnessPlanId:int?}"
@model fitnessTracker.EditModel
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h2>Editing @Model.FitnessPlan.CustomerName</h2>

<form method="post">
    <input type="hidden" asp-for="FitnessPlan.Id" />
    <div class="form-group">
        <label asp-for="FitnessPlan.CustomerName"></label>
        <input asp-for="FitnessPlan.CustomerName" class="form-control" />
        <span class="text-danger" asp-validation-for="FitnessPlan.CustomerName"></span>
    </div>

    <div class="form-group">
        <label asp-for="FitnessPlan.Pushups"></label>
        <input asp-for="FitnessPlan.Pushups" class="form-control" />
        <span class="text-danger" asp-validation-for="FitnessPlan.Pushups"></span>
    </div>

    <button type="submit" class="btn btn-primary">Save</button>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

fitnessTracker/Pages/List/List.cshtml
@page
@model fitnessTracker.ListModel
@{
    ViewData["Title"] = "List";
}

<h1>List of things</h1>


<form method="get">
    <div class="form-group">
        <div class="input-group">
            <input type="search" class="form-control" asp-for="SearchTerm" />
            <span class="input-group-btn">
                <button class="btn btn-default">
                    <i class="fas fa-search"></i>
                </button>
            </span>
        </div>
    </div>
</form>

<table class="table">
    @foreach (var plan in Model.FitnessPlans)
    {
        <partial name="_Summary" model="plan"/>
    }
</table>

<a asp-page="./Edit" class="btn btn-primary">Add new plan</a>

@Model.Message

fitnessTracker/Pages/List/NotFound.cshtml
@page
@{
    ViewData["Title"] = "NotFound";
}

<h1>NotFound</h1>


<h2>Your plan was not found</h2>

<a asp-page="./List" class="btn btn-primary">Back to list</a>

fitnessTracker/Pages/List/_Summary.cshtml
@using fitnessTracker.core
@model FitnessPlan

<div class="card">
    <div class="card-body">
        <h3>@Model.CustomerName</h3>
        <span>Pushups: @Model.Pushups</span>
    </div>
    <div class="card-footer">
        <a class="btn btn-lg" asp-page="./Detail" asp-route-fitnessPlanId="@Model.Id">
            <i class="fas fa-check"></i>
        </a>
        <a class="btn btn-lg" asp-page="./Edit" asp-route-fitnessPlanId="@Model.Id">
            <i class="fas fa-edit"></i>
        </a>
        <a class="btn btn-lg" asp-page="./Delete" asp-route-fitnessPlanId="@Model.Id">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</div>

fitnessTracker/Pages/Shared/Components/FitnessPlanCount/Default.cshtml
@model int

<div class="card card-body bg-light">
    There are @Model  FitnessPlans in the system. <a asp-page="/List/List">See them all.</a>
</div>

fitnessTracker/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - fitnessTracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/90cbb1cc30.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">fitnessTracker</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/List/List">Test page</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <vc:fitness-plan-count></vc:fitness-plan-count>
            &copy; 2020 - fitnessTracker - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

fitnessTracker/Pages/Shared/_ReactScriptsPartial.cshtml
<environment include="Development">
    <script crossorigin src="https://unpkg.com/react@16/umd/react.development.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
</environment>
<environment exclude="Development">
    <script crossorigin src="https://unpkg.com/react@16/umd/react.production.min.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js"></script>
</environment>